site_name: Допомога українцям в Норвегії 🇺🇦 🇳🇴
theme:
  name: material
  custom_dir: overrides
  palette:
      primary: custom
  language: uk
  favicon: assets/favicon.png
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.footer
    - navigation.top
    - navigation.path
    - content.tooltips
  font:
    text: Montserrat
  icon:
    annotation: material/chevron-down-circle
    logo: material/information-box
    
extra_css:
  - assets/stylesheets/extra.css

plugins:
  - search
  - git-revision-date-localized
  - htmlproofer:
      validate_external_urls: !ENV [VALIDATE_EXTERNAL_URLS, false]
      raise_error_after_finish: true
      retry_max_times: 3
      max_workers: 4
      ignore_urls:
        - https://www.vybuss.no/
        - https://www.vy.no/
        - https://t.me/*

markdown_extensions:
- footnotes
- abbr
- attr_list
- md_in_html
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.tabbed:
      alternate_style: true
- pymdownx.snippets:
      auto_append:
        - includes/links.md
copyright: Слава Україні!

nav:
    # - '🔗 Посилання на загальну інформацію': index.md
    - '🛡️ Тимчасовий колективний захист': kollektiv-beskyttelse.md
    - '👤 Індивідуальний захист (прихисток/asylum)': individuell-beskyttelse.md
    - '🆔 Документи, що видає Норвегія': dokumenter.md
    - '👨‍👩‍👧‍👦 Реєстрація батьківської відповідальності': avtale-om-foreldreansvar.md
    - '🐾 Домашні тварини з України': kjaeledyr.md
    - '🏠 Житло та тимчасове розміщення': bolig.md
    - '💵 Допомога та виплати': stotte.md
    - '📖 Інтродукційна (ознайомча) програма': introduksjonsprogram.md
    - '🚗 Автомобілі та транспортні засоби': forerkort-og-bil.md
    - '💼 Робота в Норвегії': arbeid.md
    - '🎓 Освіта': utdanning.md
    - '🩺 Медична допомога': helsehjelp.md
    - '📊 Статистика': statistikk.md
    - '❓ Хочу поставити запитання': kontakt.md
    - '🛂 Дозвіл на постійне проживання': permanent-oppholdstillatelse.md
    # - '⚖️ Юридичні посилання': lover.md
    - '✉️ Зворотній зв''язок': tilbakemelding.md
